lbs:
  source:
    #download: ["https://github.com/dotnet/coreclr/archive/v1.0.0-rc1.tar.gz"]
    download: ["https://github.com/dotnet/coreclr/archive/f1f3d1e2d33ef87a261faccfa9ad612edd696a64.tar.gz"]
