lbs:
  source:
    #download: ["http://download.mono-project.com/sources/monodevelop/monodevelop-5.10.0.871.tar.bz2"]
    download: ["https://download.solidcharity.com/tarballs/tpokorra/mono/monodevelop-6.0.1.8.tar.bz2"]
